Exception: No more <elementType> participating to slack distribution (#799)
Signed-off-by: Bertrand Rix <bertrand.rix@artelys.com>
Signed-off-by: Damien Jeandemange <damien.jeandemange@artelys.com>
(cherry picked from commit d6105cc774070dfcab3e48cb2addde39d24b64dc)